import { AppDef } from "../../lib/types";

export const SEED_APPS: Record<string, AppDef> = {
  "tsla-putwall": {
    id: "tsla-putwall",
    name: "TSLA Put Wall Sentinel",
    cat: "Quant · Options Flow",
    icon: "T",
    color: "amber",
    env: "live",
    url: "tsla-sentinel.ada-labs.io",
    type: "putwall",
    desc: "Real-time put wall monitor with morning sentinel hooks and gamma exposure heatmap.",
    runtime: { region: "us-east-1", uptime: "14d 06h", latency: "42ms", requests: "8.2k/d", errors: "0.01%" },
    log: [
      ["12:04:02", "pull options chain · tradier", "info"],
      ["12:04:03", "computing gamma exposure · 5 expiries", ""],
      ["12:04:04", "put wall detected @ $420", "ok"],
      ["12:04:04", "call wall detected @ $450", "ok"],
      ["12:04:05", "rendered · 0 errors", "ok"],
    ],
  },
  "morning-briefing": {
    id: "morning-briefing",
    name: "Morning Briefing",
    cat: "Dashboard · Recurring",
    icon: "M",
    color: "teal",
    env: "live",
    url: "briefing.ada-labs.io",
    type: "briefing",
    desc: "Bloomberg-style daily briefing with MAG-7, macro snapshot, and ticker setups.",
    runtime: { region: "us-east-1", uptime: "62d 11h", latency: "38ms", requests: "1/d", errors: "0%" },
    log: [
      ["07:00:01", "cron trigger · 7am EST", "info"],
      ["07:00:02", "multi-search · macro / MAG-7 / tickers", ""],
      ["07:00:09", "composing HTML briefing", ""],
      ["07:00:11", "sent → atila.bayat@gmail.com", "ok"],
      ["07:00:11", "delivery confirmed", "ok"],
    ],
  },
  "ipa-compendium": {
    id: "ipa-compendium",
    name: "IPA Compendium",
    cat: "Reference · 35 Patterns",
    icon: "I",
    color: "rose",
    env: "staging",
    url: "ipa.ada-labs.io",
    type: "compendium",
    desc: "Master pattern reference with QM/QML, FVG, BOS, OB, SMC methodology and empirical win rates.",
    runtime: { region: "us-east-1", uptime: "3d 02h", latency: "12ms", requests: "420/d", errors: "0%" },
    log: [
      ["09:14:22", "load workbook v3.0 · 7 sheets", "info"],
      ["09:14:22", "index 35 patterns", ""],
      ["09:14:23", "join regime memory win-rates", ""],
      ["09:14:23", "staging build ready", "warn"],
      ["09:14:23", "awaiting promotion → production", "warn"],
    ],
  },
  "ai-news-digest": {
    id: "ai-news-digest",
    name: "AI News Digest Agent",
    cat: "Agent · Scheduled 7am EST",
    icon: "A",
    color: "violet",
    env: "live",
    url: "digest.ada-labs.io",
    type: "digest",
    desc: "Autonomous AI news digest covering MAG-7, macro/Fed, and AI Leaderboard tracking.",
    runtime: { region: "us-east-1", uptime: "21d 18h", latency: "55ms", requests: "1/d", errors: "0%" },
    log: [
      ["07:00:01", "agent wake · scheduled", "info"],
      ["07:00:03", "web_search · AI / MAG-7 / macro", ""],
      ["07:00:14", "rank AI leaderboard", ""],
      ["07:00:18", "dashboard rendered", "ok"],
      ["07:00:18", "dispatched to slack + email", "ok"],
    ],
  },
  "call-wall": {
    id: "call-wall",
    name: "Call Wall Monitor",
    cat: "Quant · Dealer Flow",
    icon: "C",
    color: "amber",
    env: "live",
    url: "callwall.ada-labs.io",
    type: "putwall",
    desc: "Call wall and gamma exposure across MAG-7 with regime overlays.",
    runtime: { region: "us-east-1", uptime: "14d 06h", latency: "44ms", requests: "6.1k/d", errors: "0.02%" },
    log: [
      ["12:04:02", "pull MAG-7 chains", "info"],
      ["12:04:04", "call wall scan · 7 tickers", ""],
      ["12:04:05", "regime overlay applied", "ok"],
      ["12:04:05", "rendered · 0 errors", "ok"],
    ],
  },
  "peirce-lattice": {
    id: "peirce-lattice",
    name: "Peirce Lattice",
    cat: "Knowledge · Semiotics",
    icon: "P",
    color: "violet",
    env: "live",
    url: "peirce.ada-labs.io",
    type: "lattice",
    desc: "Interactive lattice diagram of Peirce's ten classes of signs.",
    runtime: { region: "us-east-1", uptime: "8d 14h", latency: "9ms", requests: "85/d", errors: "0%" },
    log: [
      ["10:22:01", "load lattice model", "info"],
      ["10:22:01", "render 10 sign classes", ""],
      ["10:22:02", "compute lattice edges", ""],
      ["10:22:02", "interactive · ready", "ok"],
    ],
  },
  "job-hunting": {
    id: "job-hunting",
    name: "Job Hunting Agent",
    cat: "Agent · Vercel Deploy",
    icon: "J",
    color: "teal",
    env: "dev",
    url: "jobs.ada-labs.io",
    type: "generic",
    desc: "Autonomous job search with React UI and serverless API proxy.",
    runtime: { region: "vercel · iad1", uptime: "—", latency: "120ms", requests: "12/d", errors: "0.4%" },
    log: [
      ["15:31:08", "serverless cold start", "info"],
      ["15:31:10", "api/claude.js · proxy ready", ""],
      ["15:31:11", "dev preview built", "warn"],
      ["15:31:11", "not promoted", "warn"],
    ],
  },
  "self-improving-wiki": {
    id: "self-improving-wiki",
    name: "Self-Improving Agents",
    cat: "Wiki · Research Hub",
    icon: "S",
    color: "rose",
    env: "dev",
    url: "wiki.ada-labs.io/self-improving-agents",
    type: "wiki",
    desc: "Karpathy-style wiki on autonomous agent self-improvement with 10 papers indexed.",
    runtime: { region: "us-east-1", uptime: "2d 09h", latency: "11ms", requests: "38/d", errors: "0%" },
    log: [
      ["11:02:01", "load wiki · 28 pages", "info"],
      ["11:02:01", "index 10 sources", ""],
      ["11:02:02", "knowledge graph linked", "ok"],
      ["11:02:02", "dev preview ready", "warn"],
    ],
  },
};

